server:
  port: 8081

spring:
  security:
    user:
      name: admin        # Replace with your desired username
      password: admin123 # Replace with your desired password
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: "iamdkj237"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

api:
  url: "api.tablebite.in"
  port: 8081
external:
  api:
    url: "http://13.48.177.20:8081"

